# Generated by Django 5.2 on 2025-04-14 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import uuid
from django.utils import timezone


def generate_reference_ids(apps, schema_editor):
    Payroll = apps.get_model('payroll', 'Payroll')
    for payroll in Payroll.objects.all():
        year = payroll.pay_period.year
        month = payroll.pay_period.month
        unique_id = str(uuid.uuid4())[:8]
        payroll.reference_id = f"PAY-{year}-{month:02d}-{payroll.employee_id}-{unique_id}"
        payroll.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('human_resource', 'Human Resource'), ('finance', 'Finance'), ('design', 'Design')], max_length=20, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('probation', 'Probation')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    max_length=50,
                    unique=True,
                    help_text="Unique reference ID for this payroll",
                    editable=False,
                    null=True
                )),
                ('pay_period', models.DateField(default=django.utils.timezone.now, help_text='Period for which this payroll is generated')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retirement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retirement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.employee')),
            ],
            options={
                'ordering': ['-pay_period', 'employee__first_name'],
                'unique_together': {('employee', 'pay_period')},
            },
        ),
        migrations.RunPython(generate_reference_ids),
        migrations.AlterField(
            model_name='payroll',
            name='reference_id',
            field=models.CharField(
                max_length=50,
                unique=True,
                help_text="Unique reference ID for this payroll",
                editable=False
            ),
        ),
    ]
