# Generated by Django 5.2 on 2025-04-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='position',
        ),
    ]
