# Generated by Django 5.2 on 2025-04-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
