# Generated by Django 5.2 on 2025-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('probation', 'Probation')], default='active', max_length=10),
        ),
    ]
