# Generated by Django 5.2 on 2025-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('human_resource', 'Human Resource'), ('finance', 'Finance'), ('design', 'Design')], max_length=20, null=True),
        ),
    ]
