# Generated by Django 5.2 on 2025-04-11 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-pay_period', 'employee__first_name']},
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_period',
            field=models.DateField(default=django.utils.timezone.now, help_text='Period for which this payroll is generated'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'pay_period')},
        ),
    ]
